# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Cycle.delete_all
Cycle.create!(Brand: "Trek", Color: 'red', Category: 'mountain', Price: '12000', description: 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium', location: 'Meguro', picture_url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQC1hxBQzHRQXLyJaf-SFeKPbMErhvzMmw30HwTy8YL5gDe7MCm')
Cycle.create!(Brand: "Trek", Color: 'blue', Category: 'hybrid', Price: '10000', description: 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium', location: 'Setagaya', picture_url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSPxVEbg0IP5oWmMcKasAHlHGbIIt_Fp0OSXSRC4w-vgdzDr8Yh')
Cycle.create!(Brand: "Trek", Color: 'green', Category: 'road', Price: '30000', description: 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium', location: 'Roppongi', picture_url: 'https://isabela.iweb.co.uk/image/aHR0cHM6Ly93d3cucmFsZWlnaC5jby51ay9tZWRpYS9jYXRhbG9nL3Byb2R1Y3QvaC9lL2hlbGlvbl8xaHRfZ3JlZW5faGUxMTdncm4tMl8xXzFfMV8xXzFfMV81XzIuanBn?q=75&w=2646&h=2646&e=1209600&t=outbound')
Cycle.create!(Brand: "Trek", Color: 'black', Category: 'hybrid', Price: '15000', description: 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium', location: 'Ikebukuro', picture_url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSifbGh7cpT8X0PFwz_Sk2JghK9du6KRxWC4DOlWh5cedY4z-7w')
Cycle.create!(Brand: "Giant", Color: 'red', Category: 'mountain', Price: '12000', description: 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium', location: 'Meguro', picture_url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQC1hxBQzHRQXLyJaf-SFeKPbMErhvzMmw30HwTy8YL5gDe7MCm')
Cycle.create!(Brand: "Giant", Color: 'blue', Category: 'hybrid', Price: '10000', description: 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium', location: 'Setagaya', picture_url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSPxVEbg0IP5oWmMcKasAHlHGbIIt_Fp0OSXSRC4w-vgdzDr8Yh')
Cycle.create!(Brand: "Giant", Color: 'green', Category: 'road', Price: '30000', description: 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium', location: 'Roppongi', picture_url: 'https://isabela.iweb.co.uk/image/aHR0cHM6Ly93d3cucmFsZWlnaC5jby51ay9tZWRpYS9jYXRhbG9nL3Byb2R1Y3QvaC9lL2hlbGlvbl8xaHRfZ3JlZW5faGUxMTdncm4tMl8xXzFfMV8xXzFfMV81XzIuanBn?q=75&w=2646&h=2646&e=1209600&t=outbound')
Cycle.create!(Brand: "Giant", Color: 'black', Category: 'hybrid', Price: '15000', description: 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium', location: 'Ikebukuro', picture_url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSifbGh7cpT8X0PFwz_Sk2JghK9du6KRxWC4DOlWh5cedY4z-7w')
Cycle.create!(Brand: "Cannondale", Color: 'red', Category: 'mountain', Price: '12000', description: 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium', location: 'Meguro', picture_url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQC1hxBQzHRQXLyJaf-SFeKPbMErhvzMmw30HwTy8YL5gDe7MCm')
Cycle.create!(Brand: "Cannondale", Color: 'blue', Category: 'hybrid', Price: '10000', description: 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium', location: 'Setagaya', picture_url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSPxVEbg0IP5oWmMcKasAHlHGbIIt_Fp0OSXSRC4w-vgdzDr8Yh')
Cycle.create!(Brand: "Cannondale", Color: 'green', Category: 'road', Price: '30000', description: 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium', location: 'Roppongi', picture_url: 'https://isabela.iweb.co.uk/image/aHR0cHM6Ly93d3cucmFsZWlnaC5jby51ay9tZWRpYS9jYXRhbG9nL3Byb2R1Y3QvaC9lL2hlbGlvbl8xaHRfZ3JlZW5faGUxMTdncm4tMl8xXzFfMV8xXzFfMV81XzIuanBn?q=75&w=2646&h=2646&e=1209600&t=outbound')
Cycle.create!(Brand: "Cannondale", Color: 'black', Category: 'hybrid', Price: '15000', description: 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium', location: 'Ikebukuro', picture_url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSifbGh7cpT8X0PFwz_Sk2JghK9du6KRxWC4DOlWh5cedY4z-7w')
Cycle.create!(Brand: "Specialized", Color: 'red', Category: 'mountain', Price: '12000', description: 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium', location: 'Meguro', picture_url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQC1hxBQzHRQXLyJaf-SFeKPbMErhvzMmw30HwTy8YL5gDe7MCm')
Cycle.create!(Brand: "Specialized", Color: 'blue', Category: 'hybrid', Price: '10000', description: 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium', location: 'Setagaya', picture_url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSPxVEbg0IP5oWmMcKasAHlHGbIIt_Fp0OSXSRC4w-vgdzDr8Yh')
Cycle.create!(Brand: "Specialized", Color: 'green', Category: 'road', Price: '30000', description: 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium', location: 'Roppongi', picture_url: 'https://isabela.iweb.co.uk/image/aHR0cHM6Ly93d3cucmFsZWlnaC5jby51ay9tZWRpYS9jYXRhbG9nL3Byb2R1Y3QvaC9lL2hlbGlvbl8xaHRfZ3JlZW5faGUxMTdncm4tMl8xXzFfMV8xXzFfMV81XzIuanBn?q=75&w=2646&h=2646&e=1209600&t=outbound')
Cycle.create!(Brand: "Specialized", Color: 'black', Category: 'hybrid', Price: '15000', description: 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium', location: 'Ikebukuro', picture_url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSifbGh7cpT8X0PFwz_Sk2JghK9du6KRxWC4DOlWh5cedY4z-7w')
